version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5444:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1556457Mm.
      POSTGRES_DB: road-mates-db
    networks:
      - RoadMates
networks:
  RoadMates: